---
title: "Networks"
author: "Shira Salingré"
output: 
  html_document:
    theme: paper
    toc: true
    toc_float: 
      collapse: FALSE
      smooth_scroll: FALSE
---

```{r setup, include=FALSE}
source("R/packages.R")
source("R/functions.R")
source('R/models.R', echo = FALSE)

guilds <- list(groupers = colnames(species_mats$grps_mat)[1:4],
               diplodus = colnames(species_mats$dip_mat)[1:4],
               herbivores = colnames(species_mats$herb_mat)[1:4])

```

# Poisson models

## Overall network

```{r}
p_net_grps <- plot_graph(poisson_models$grps_pois, "Groupers")

p_net_dip <- plot_graph(poisson_models$dip_pois, "Seabreams")

p_net_herb <- plot_graph(poisson_models$herb_pois, "Herbivores")

p_net_grps + p_net_dip + p_net_herb

```

## Temperature Gradient

**Groupers**

```{r}
plotMRF_net_cont(species_mats$grps_mat, poisson_models$grps_pois, node_names = guilds$groupers, covariate = "temp")

```

**Seabreams**

```{r}
plotMRF_net_cont(species_mats$dip_mat, poisson_models$dip_pois, node_names = guilds$diplodus, covariate = "temp")

```

**Herbivores**

```{r}
plotMRF_net_cont(species_mats$herb_mat, poisson_models$herb_pois, node_names = guilds$herbivores, covariate = "temp")

```

## In and out of MPAs

**Groupers**

```{r}
plotMRF_net_factor(species_mats$grps_mat, poisson_models$grps_pois, guilds$grouper, covariate = "mpa")

```

**Seabreams**

```{r}
plotMRF_net_factor(species_mats$dip_mat, poisson_models$dip_pois, guilds$diplodus, covariate = "mpa")

```

**Herbivores**

```{r}
plotMRF_net_factor(species_mats$herb_mat, poisson_models$herb_pois, guilds$herbivores, covariate = "mpa")

```


# Biomass models

## Overall network

```{r}
net_grps <- plot_graph(biomass_models$grps_mass, "Groupers")

net_dip <- plot_graph(biomass_models$dip_mass, "Seabreams")

net_herb <- plot_graph(biomass_models$herb_mass, "Herbivores")

net_grps + net_dip + net_herb

```

## Temperature Gradient

**Groupers**

```{r}
plotMRF_net_cont(species_mats_mass$grps_mass_mat, biomass_models$grps_mass, node_names = guilds$groupers, covariate = "temp")

```

**Seabreams**

```{r}
plotMRF_net_cont(species_mats_mass$dip_mass_mat, biomass_models$dip_mass, node_names = guilds$diplodus, covariate = "temp")

```

**Herbivores**

```{r}
plotMRF_net_cont(species_mats_mass$herb_mass_mat, biomass_models$herb_mass, node_names = guilds$herbivores, covariate = "temp")

```

## In and out of MPAs

**Groupers**

```{r}
plotMRF_net_factor(species_mats_mass$grps_mass_mat, biomass_models$grps_mass, guilds$grouper, covariate = "mpa")

```

**Seabreams**

```{r}
plotMRF_net_factor(species_mats_mass$dip_mass_mat, biomass_models$dip_mass, guilds$diplodus, covariate = "mpa")

```

**Herbivores**

```{r}
plotMRF_net_factor(species_mats_mass$herb_mass_mat, biomass_models$herb_mass, guilds$herbivores, covariate = "mpa")

```


